services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cinematchdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=cinematch'
    ports:
      - '5432'
  sentiment:
    build: ./sentiment-analysis
    ports:
      - '5000:5000'
