services:
  postgres:
    image: 'postgres:latest'
    container_name: cinematch-postgres
    environment:
      - 'POSTGRES_DB=cinematchdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=cinematch'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
  sentiment:
    build: ./sentiment-analysis
    container_name: sentiment_service
    ports:
      - '5000:5000'