services:
  app:
    image: ghcr.io/cinematch-app:latest
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASS}
      - spring.datasource.url=${DB_URL}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    env_file:
      .env
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    container_name: cinematch-postgres
    environment:
      POSTGRES_DB: cinematchdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
    driver: local
