services:
  postgres:
    image: 'postgres:latest'
    container_name: cinematch-postgres
    environment:
      - 'POSTGRES_DB=cinematchdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=cinematch'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  sentiment:
    build: ./sentiment-analysis
    container_name: sentiment_service
    ports:
      - '5000:5000'
  face_detection:
    build: ./face_detection
    container_name: face_detection
    ports:
      - '5001:5001'    
volumes:
  postgres_data:
    driver: local
    