services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cinematchdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=cinematch'
    ports:
      - '10514:5432'